variables:
    ascName: oryxSP
    acrName: oryxdevmcr.azurecr.io
    skipComponentGovernanceDetection: true
  
jobs:
- template: ../templates/_buildimageBasesJobTemplate.yml
  parameters:
    displayName: Build python runtime buster base images
    scriptPath: ./build/buildRunTimeImageBases.sh
    imageDir: python
    imageDebianFlavor: buster
    artifactsFileName: python-runtimeimage-bases-buster.txt
    jobName: Build_Buster_BaseImages

- job: Release_PythonRuntimeBaseImage
  dependsOn: 
    - Build_Buster_BaseImages
  displayName: Push images to MCR
  timeoutInMinutes: 250
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - template: ../templates/_releaseBaseImagesStepTemplate.yml
      parameters:
        baseImageName: 'python'
